version: 2
jobs:
  build1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: echo "Test --> OK!"
  build2:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: CI=true
workflows:
  version: 2
  test_builds:
    jobs:
      - build1
      - build2
        